### ISSUE TITLE
Unable to install on Odoo 14.0 on AWS Bitnami

### ISSUE THREAD

**Issue by NoobFullStack** [OCA/l10n-portugal#56]
I'm trying to install this module in Odoo 14.0 on AWS (bitnami ami) and receive the following error in install. 

Error:
Odoo Server Error

```
Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/modules/module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/bitnami/odoo/addons/l10n_pt_saft/__init__.py", line 23, in <module>
    import l10n_pt_saft
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ModuleNotFoundError: No module named 'l10n_pt_saft'
```

**Comment by dreispt** [comment]
Hello, the `l10n_pt_saft` is not available for version 14.0.
You can see the list of v14 available modules here: https://github.com/OCA/l10n-portugal/blob/14.0/README.md

Let me know if I can help further.

Thanks
